/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_haveimgfun_LibImgFun */

#ifndef _Included_com_example_haveimgfun_LibImgFun
#define _Included_com_example_haveimgfun_LibImgFun
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_haveimgfun_LibImgFun
 * Method:    processImg
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_haveimgfun_LibImgFun_processImg
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
